version: '2'
services:
  web:
    build: .
    image: shaimaalsharif/nest-repo-1:3.0
    restart: always
    environment:
      NODE_ENV: development
    ports:
      - "80:5000"
    command: npm start
  

   